### ISSUE TITLE
[Feature Request] Pushover notifications

### ISSUE THREAD

**Issue by mpeterson** [rocket-pool/smartnode#818]
Pushover is a very commonly used notification system for people that have homelabs. It is also very easy to configure and use. It would be great to see it supported by the smartnode TUI.

**Comment by mpeterson** [comment]
For now my workaround is:

- `cp ~/.rocketpool/alerting/alertmanager.yml ~/alertmanager.yml`
- modified `/alertmanager.yml` to have these contents in the receivers section:
  ```yaml
  receivers:
    - name: "node_operator_default"
      pushover_configs:
        - token: REDACTED
          user_key: REDACTED
    
    - name: "node_operator_no_resolved"
      pushover_configs:
        - token: REDACTED
          user_key: REDACTED
  ```
- modifed `~/.rocketpool/override/alertmanager.yml` to have these contents:
   ```yaml
   # Enter your own customizations for the alertmanager container here. These changes will persist after upgrades, so you only need to do them once.
  #
  # See https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
  # for more information on overriding specific parameters of docker-compose files.
  
  services:
    alertmanager:
      x-rp-comment: Add your customizations below this line
  
      volumes:
        - "~/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
        - "alertmanager-data:/alertmanager"
   ```
